# -*- coding: utf-8 -*-
"""day_22_pandas_profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qsShSbSds5R5psa9ifhEUiEtO_tSTNFw
"""

!pip install fg-data-profiling

import pandas as pd

df=pd.read_csv("/content/airlines_flights_data.csv")

from data_profiling import ProfileReport

profile=ProfileReport(df,title=" Profile Report of flights dataset")

profile.to_file("flights_report.html")

df.head()